# Generated by Django 5.1.4 on 2025-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xml_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe_title', models.CharField(max_length=2000)),
                ('cpe_22_uri', models.TextField()),
                ('cpe_23_uri', models.TextField()),
                ('reference_links', models.TextField()),
                ('cpe_22_deprecation_date', models.DateField()),
                ('cpe_23_deprecation_date', models.DateField()),
            ],
        ),
    ]
